### ISSUE TITLE
We hope you can open-source your datasets and preprocessing methods

### ISSUE THREAD

**Issue by Tony-Frank** [hkthirano/UAP-COVID-Net#1]
Gratefully if you hope you can open-source your datasets and preprocessing methods.

**Comment by kztakemoto** [comment]
See https://github.com/lindawangg/COVID-Net for the details of the dataset construction and preprocessing. 

`create_COVIDx_v2.ipynb`, used in our study, is currently unavailable in the main branch; however, you can find it from https://github.com/lindawangg/COVID-Net/blob/b5e260ee34aadf391277e0ad34ac1323885a0351/create_COVIDx_v2.ipynb
